version: "2"

networks:
  postgres:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bd20182
      PGDATA: /data/postgres
    volumes:
      - /data/postgres:/data/postgres
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    container_name: postgres_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - /data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - postgres
    restart: unless-stopped

  db-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: db-api
    environment:
      PG_USER: postgres
      PG_PASSWORD: bd20182
    volumes:
      - ./rest-go:/go/src/rest-go
    working_dir: /go/src/rest-go
    command: /bin/bash -c 'go run main.go'
    ports:
      - "80:3000"
    networks:
      - postgres
    restart: unless-stopped
